<?php if($res->getUser()->getId()): ?> 
    <form method="post" action="addBook">
        <div class="mb-3">
            <label for="titulo" class="form-label">
                Titulo:
            </label>
            <input name="titulo" type="text" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="genero" class="form-label">
                Genero:
            </label>
            <input name="genero" type="text" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="editorial" class="form-label">
                Editorial:
            </label>
            <input name="editorial" type="text" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="id_libreria" class="form-label">
                Libreria:
            </label>
            <select name="id_libreria" class="form-control" required>
                <?php foreach($librerias as $libreria): ?>
                    <option value="<?= htmlspecialchars($libreria->id_libreria)?>"><?= htmlspecialchars($libreria->nombre)?></option>
            <?php endforeach ?>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Agregar</button>
</form>
<?php endif ?>