<?php require './templates/layout/header.phtml' ?>
<?php require './templates/addLibrary.phtml' ?>

<h2>Lista de Librerías</h2>

<ul class="list-group">
    <?php foreach ($librerias as $libreria): ?>
        <li class="list-group-item item-task">
            <div class="label">
                <b><?= htmlspecialchars($libreria->nombre) ?></b> | Dirección: <?= htmlspecialchars($libreria->direccion) ?>
            </div>
            <?php if($res->getUser()->getId()): ?>
                <div class="actions">
                    <a href="modifyLibrary/<?= $libreria->id_libreria ?>" type="button" class='btn btn-warning'>Editar</a>
                    <a href="deleteLibrary/<?= $libreria->id_libreria ?>" type="button" class='btn btn-danger'>Borrar</a>
                    <a href="infoLibrary/<?= $libreria->id_libreria ?>" type="button" class='btn btn-info'>Libros</a>
                </div>
            <?php endif; ?> 
        </li>
    <?php endforeach; ?>
</ul>

<p class="mt-3"><small>Mostrando <?= count($librerias) ?> librerías</small></p>

<?php require './templates/layout/footer.phtml'; ?>