<?php require './templates/layout/header.phtml' ?>
<?php require './templates/addBook.phtml' ?>

<ul class="list-group">
<?php foreach($libros as $libro): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= htmlspecialchars($libro->nombre_libro) ?></b> | Genero <?=htmlspecialchars($libro->genero)?> | ( Editorial <?=htmlspecialchars($libro->editorial) ?> )
        </div>
        <div class="actions">
            <!-- <?php if(!$libro->id_libro): ?> 
                <a href="finalizar/<?= $libro->id_libro ?>" type="button" class='btn btn-success btn-sm ml-auto'>Finalizar</a> 
            <?php endif ?> -->
            <a href="modifyBook/<?= $libro->id_libro ?>" type="button" class='btn btn-warning'>Editar</a>
            <a href="delete/<?= $libro->id_libro ?>" type="button" class='btn btn-danger'>Borrar</a>
            <a href="infoBook/<?= $libro->id_libro ?>" type="button" class='btn btn-info'>Ver mas</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <!-- <?=$count?> --> libros</small></p>


<?php require './templates/layout/footer.phtml' ?>