<?php require './templates/layout/header.phtml' ?>

    <form method="post">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">
                Email
            </label>
            <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                <div id="emailHelp" class="form-text">
                    Nunca compartiremos su correo electrónico con nadie más.
                </div>
        </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">
                    Contraseña
                </label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1" required>
            </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

<?php require './templates/layout/footer.phtml' ?>