<?php require './templates/layout/header.phtml' ?>
    <?php if($error):  ?>
        <p class="fs-3"><?= $error ?></p>
    <?php endif ?>
    <form method="post" action="login">
        <div class="mb-3">
            <label for="email" class="form-label">
                Email o usuario
            </label>
            <input name="email" type="text" class="form-control" aria-describedby="emailHelp" required>
                <div id="emailHelp" class="form-text">
                    Nunca compartiremos su correo electrónico con nadie más.
                </div>
        </div>
            <div class="mb-3">
                <label for="password" class="form-label">
                    Contraseña
                </label>
                <input name="password" type="password" class="form-control" required>
            </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

<?php require './templates/layout/footer.phtml' ?>